### PR TITLE
Adding global gulp installation

### PR DESCRIPTION
**Pull request by iambmelt**
@Ricalo can you test this works on Windows 10?

### CODE REVIEW

**Comment by Ricalo** [comment]
I'll try this tomorrow morning. Are you assuming that I don't have gulp installed? Or should I install gulp beforehand?

**Comment by iambmelt** [comment]
@Ricalo I'm assuming you *don't* have it installed. Ideally, the instructions work for your exactly as written :+1:

**Comment by Ricalo** [comment]
Ok, trying this *now*

**Comment by Ricalo** [comment]
The web server is up and running, there was a warning in the output, probably nothing to worry about, but here's the output

```
ricalo@MyBox /d/code/O365-Nodejs-Unified-API-Connect (hotifx-windows)
$  npm install && npm install --global gulp && gulp
```
**npm WARN optional dep failed, continuing fsevents@0.3.8**
```
debug@2.2.0 node_modules\debug
└── ms@0.7.1

cookie-parser@1.3.5 node_modules\cookie-parser
├── cookie@0.1.3
└── cookie-signature@1.0.6

serve-favicon@2.3.0 node_modules\serve-favicon
├── fresh@0.3.0
├── etag@1.7.0
├── parseurl@1.3.0
└── ms@0.7.1

morgan@1.6.1 node_modules\morgan
├── basic-auth@1.0.3
├── on-headers@1.0.0
├── depd@1.0.1
└── on-finished@2.3.0 (ee-first@1.1.1)

express-session@1.11.3 node_modules\express-session
├── cookie@0.1.3
├── cookie-signature@1.0.6
├── on-headers@1.0.0
├── parseurl@1.3.0
├── utils-merge@1.0.0
├── depd@1.0.1
├── crc@3.3.0
└── uid-safe@2.0.0 (base64-url@1.2.1)

cookie-session@1.2.0 node_modules\cookie-session
├── on-headers@1.0.0
└── cookies@0.5.0 (keygrip@1.0.1)

express@4.13.3 node_modules\express
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── escape-html@1.0.2
├── vary@1.0.1
├── merge-descriptors@1.0.0
├── array-flatten@1.1.1
├── content-type@1.0.1
├── etag@1.7.0
├── parseurl@1.3.0
├── path-to-regexp@0.1.7
├── serve-static@1.10.0
├── content-disposition@0.5.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── qs@4.0.0
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.6)

body-parser@1.13.3 node_modules\body-parser
├── content-type@1.0.1
├── bytes@2.1.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── http-errors@1.3.1 (inherits@2.0.1, statuses@1.2.1)
├── qs@4.0.0
├── raw-body@2.1.3 (unpipe@1.0.0)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── iconv-lite@0.4.11

gulp@3.9.0 node_modules\gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── v8flags@2.0.10 (user-home@1.1.1)
├── tildify@1.1.1 (os-homedir@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (object-assign@3.0.0, array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, beeper@1.1.0, replace-ext@0.0.1, vinyl@0.
5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-nodemon@2.0.4 node_modules\gulp-nodemon
├── colors@1.1.2
├── event-stream@3.3.1 (duplexer@0.1.1, from@0.1.3, stream-combiner@0.0.4, pause-stream@0.0.11, map-stream@0.1.0, through@2.3.8, split@0.3.3)
└── nodemon@1.5.1 (undefsafe@0.0.3, es6-promise@3.0.2, minimatch@0.3.0, touch@1.0.0, lodash.defaults@3.1.2, ps-tree@0.0.3, chokidar@1.0.6, update-notifier@0.5.0)

hbs@3.1.1 node_modules\hbs
├── walk@2.2.1 (forEachAsync@2.2.1)
└── handlebars@3.0.0 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)

adal-node@0.1.16 node_modules\adal-node
├── async@1.4.2
├── node-uuid@1.4.1
├── xmldom@0.1.19
├── underscore@1.8.3
├── xpath.js@1.0.6
├── jws@3.1.0 (base64url@1.0.4, jwa@1.1.0)
├── request@2.62.0 (aws-sign2@0.5.0, tunnel-agent@0.4.1, forever-agent@0.6.1, stringstream@0.0.4, caseless@0.11.0, oauth-sign@0.8.0, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, ext
end@3.0.0, qs@5.1.0, combined-stream@1.0.5, mime-types@2.1.6, http-signature@0.11.0, bl@1.0.0, tough-cookie@2.0.0, hawk@3.1.0, har-validator@1.8.0)
└── date-utils@1.2.17
C:\Users\ricardol\AppData\Roaming\npm\gulp -> C:\Users\ricardol\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
gulp@3.9.0 C:\Users\ricardol\AppData\Roaming\npm\node_modules\gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.1 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (supports-color@2.0.0, escape-string-regexp@1.0.3, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, object-assign@3.0.0, beeper@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, vinyl@0.
5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
[11:03:11] Using gulpfile d:\code\O365-Nodejs-Unified-API-Connect\gulpfile.js
[11:03:11] Starting 'default'...
[11:03:11] Finished 'default' after 2.43 ms
[11:03:11] [nodemon] v1.5.1
[11:03:11] [nodemon] to restart at any time, enter `rs`
[11:03:11] [nodemon] watching: *.*
[11:03:11] [nodemon] starting `node app.js`
GET / 302 10.925 ms - 66
GET /login 200 97.859 ms - 1307
GET /stylesheets/style.css 200 3.406 ms - 683
```

**Comment by iambmelt** [comment]
Thanks @Ricalo :+1:

**Pull request merged**
